image: 51systems/gitlab-ci-android

before_script:
  - export GRADLE_USER_HOME=/cache/.gradle
  - android-update-sdk build-tools-25.0.1,android-25
  - android-update-sdk extra-android-m2repository,extra-google-m2repository,extra-google-google_play_services
  - chmod +x ./gradlew


cache:
  paths:
     - .gradle/wrapper
     - .gradle/caches

stages:
  - test
  - assemble
  - publish


test:unit:
  stage: test
  script:
    - ./gradlew testDebugUnitTest
  artifacts:
    name: "Tests-${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"
    when: always
    expire_in: 1 weeks
    paths:
      - "**/build/reports/tests"
  tags:
    - docker

test:release:
  stage: test
  script:
    - ./gradlew testReleaseUnitTest
  artifacts:
   name: "Tests-${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"
   when: always
   expire_in: 1 weeks
   paths:
     - "**/build/reports/tests"
  when: on_success
  only:
    - tags
  tags:
    - docker

test:instrumentation:24:
  stage: test
  image: 51systems/gitlab-ci-android-emulator-24
  script:
    - android-run-emulator nexus5_24 bash ./gradlew connectedAndroidTest
  artifacts:
    name: "Tests-Instrumentation-21-${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"
    when: always
    expire_in: 1 weeks
    paths:
      - "**/build/reports/androidTests"
  when: on_success
  only:
    - tags
  tags:
    - docker
